name: e-lection

services:
    backend:
        image: ghcr.io/sonicsasha/election-backend:latest
        container_name: eLection-backend
        volumes:
            -   type: bind
                source: ./backend.env
                target: /usr/src/eLection-backend/.env
        restart: always
    frontend:
        image: ghcr.io/sonicsasha/election-frontend:latest
        container_name: eLection-frontend
        volumes:
            -   type: bind
                source: ./locales/
                target: /usr/share/nginx/html/locales/custom
            -   type: bind
                source: ./stylesheet.css
                target: /usr/share/nginx/html/stylesheet_custom.css
            -   type: bind
                source: ./bg.png
                target: /usr/share/nginx/html/img/bg.png
            -   type: bind
                source: ./icon.svg
                target: /usr/share/nginx/html/img/icon.svg
        depends_on:
          - backend
        restart: always
    nginx:
        image: nginx:mainline-alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          - ./sslcert:/etc/nginx/sslcert
        ports:
          - 443:443
          - 80:80 # The reverse proxy should automatically redirect to use the more secure 443 port.
        container_name: reverse-proxy
        depends_on:
          - backend
          - frontend
        restart: always