name: Release workflow
run-name: Running release workflow for ${{ github.event.release.tag_name }}

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Render deployment
        env:
          FRONTEND_DEPLOY_TRIGGER: ${{ secrets.FRONTEND_DEPLOYURL }}
          BACKEND_DEPLOY_TRIGGER: ${{ secrets.BACKEND_DEPLOYURL }}
        run: |
          curl $FRONTEND_DEPLOY_TRIGGER
          curl $BACKEND_DEPLOY_TRIGGER
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: lts
      - name: Create Docker template
        run: node create-docker-template.js
      - name: Add Docker template to release
        uses: actions/upload-artifact@v4
        with:
          path: /dockerTemplate/
      - name: Upload the template to release
        uses: softprops/action-gh-release@v2
        with:
          files: /dockerFile
          tag_name: ${{ github.event.release.tag_name }}

