name: Release workflow
run-name: Running release workflow for ${{ github.event.release.tag_name }}

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a Render deployment
        env:
          FRONTEND_DEPLOY_TRIGGER: ${{ secrets.FRONTEND_DEPLOYURL }}
          BACKEND_DEPLOY_TRIGGER: ${{ secrets.BACKEND_DEPLOYURL }}
        run: |
          curl $FRONTEND_DEPLOY_TRIGGER
          curl $BACKEND_DEPLOY_TRIGGER
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Create Docker template
        run: node create-docker-template.js
      - name: Upload the template to release
        uses: softprops/action-gh-release@v2
        with:
          files: dockerTemplate/
          tag_name: ${{ github.event.release.tag_name }}

